<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\Fonts\RussoOne-Regular.ttf" />
    <None Remove="Assets\Images\bgImg.jpeg" />
    <None Remove="Assets\Sounds\bg_sounds.mp3" />
    <None Remove="Assets\Sounds\cannon_shot.wav" />
    <None Remove="Assets\Sounds\click.wav" />
    <None Remove="Assets\Sounds\hit.wav" />
    <None Remove="Assets\Sounds\miss.wav" />
    <None Remove="Assets\Sounds\start_menu_music.mp3" />
    <None Remove="Assets\Sounds\sunk.wav" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\Sounds\bg_sounds.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Sounds\cannon_shot.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Sounds\click.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Sounds\hit.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Sounds\miss.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Sounds\start_menu_music.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\Sounds\sunk.wav">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Fonts\RussoOne-Regular.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Assets\Images\bgImg.jpeg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
